version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/code/init.sql 
    ports:
      - "5432:5432"
volumes:
  postgres_data:
